### PR TITLE
Sound Null-Safety

### PR DESCRIPTION
**Pull request by i-celeste-aurora**

### CODE REVIEW

**Review by AmirElkess — APPROVED** [review]

**Comment by vkbaloda** [comment]
Hi Amir & Imdat, can you also publish this version to pub.dev, it would be really helpful.

**Comment by i-celeste-aurora** [comment]
Hi Amir, thank you for merging. Can you publish this to pub.dev? Then I can remove my fork.

**Comment by AmirElkess** [comment]
> Hi Amir & Imdat, can you also publish this version to pub.dev, it would be really helpful.

Done. Check if the library is functioning properly from your side.

**Comment by AmirElkess** [comment]
> Hi Amir, thank you for merging. Can you publish this to pub.dev? Then I can remove my fork.

Hey imdat, Thanks for the PR, I published the latest version to pub.dev.

**Pull request merged**
